# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SNDL
email: gishsteven@gmail.com
description: Some guy who likes coffee and crawfish.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stevennamdangle.com/" # the base hostname & protocol for your site
github_username: gishsteven
favicon: "images/favicon.ico"

# Build settings
markdown: kramdown

theme: jekyll-theme-midnight
plugins:
 - jekyll-feed
 - jekyll-seo-tag
